# Generated by Django 6.0.5 on 2026-06-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('details', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('technologies', models.JSONField(default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True, max_length=500, null=True)),
                ('live_url', models.URLField(blank=True, max_length=500, null=True)),
                ('category', models.CharField(choices=[('AI', 'Artificial Intelligence'), ('ML', 'Machine Learning'), ('Web', 'Web Development'), ('Networking', 'Network Engineering'), ('Cybersecurity', 'Cybersecurity'), ('Data', 'Data Analytics')], default='Web', max_length=50)),
                ('featured', models.BooleanField(default=False)),
                ('year', models.CharField(default='2024', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
