# Generated by Django 6.0.5 on 2026-06-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.TextField()),
                ('authors', models.CharField(max_length=300)),
                ('journal', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=4)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='publications/')),
                ('pdf_url', models.URLField(blank=True, max_length=500, null=True)),
                ('doi_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
