# Generated by Django 6.0.5 on 2026-06-01 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('AI', 'AI & Machine Learning'), ('Networking', 'Cybersecurity & Networks'), ('General', 'General Software Engineer')], max_length=50, unique=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('file_url', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
